server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 0.0.0.0
      useServerHeader: false
      useDateHeader: false
      useForwardedHeaders: false
  adminConnectors:
    - type: http
      port: 8081
      acceptorThreads: 1
      selectorThreads: 1
  requestLog:
    appenders: []

logging:
  level: WARN
  loggers:
    com.fabfitfun: DEBUG
